import type Metadata from 'next'

import RootProvider from '@/providers/RootProvider'

import Rendering from '@/views/components/core/Rendering'

import Instana from '@/views/components/common/Instana'
import AppContent from '@/views/components/common/AppContent'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <RootProvider>
        <head>
          <Instana />
        </head>
        <body>
          <Rendering>
            <AppContent>{children}</AppContent>
          </Rendering>
        </body>
      </RootProvider>
    </html>
  )
}
