import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Stack } from '@mui/material'

import RootProvider from '@/providers/RootProvider'

import NavBar from '@/views/components/common/Navbar'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <RootProvider>
          <Stack alignItems="center">
            <Stack width={425} height="100vh" bgcolor="background.default">
              <NavBar />
              {children}
            </Stack>
          </Stack>
        </RootProvider>
      </body>
    </html>
  )
}
